// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/postauth/postauth.proto

package postauth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Postauth service

func NewPostauthEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Postauth service

type PostauthService interface {
	Auth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type postauthService struct {
	c    client.Client
	name string
}

func NewPostauthService(name string, c client.Client) PostauthService {
	return &postauthService{
		c:    c,
		name: name,
	}
}

func (c *postauthService) Auth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Postauth.Auth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Postauth service

type PostauthHandler interface {
	Auth(context.Context, *Request, *Response) error
}

func RegisterPostauthHandler(s server.Server, hdlr PostauthHandler, opts ...server.HandlerOption) error {
	type postauth interface {
		Auth(ctx context.Context, in *Request, out *Response) error
	}
	type Postauth struct {
		postauth
	}
	h := &postauthHandler{hdlr}
	return s.Handle(s.NewHandler(&Postauth{h}, opts...))
}

type postauthHandler struct {
	PostauthHandler
}

func (h *postauthHandler) Auth(ctx context.Context, in *Request, out *Response) error {
	return h.PostauthHandler.Auth(ctx, in, out)
}
