<?php
/**
 * link: http://www.zjhejiang.com/
 * copyright: Copyright (c) 2018 浙江禾匠信息科技有限公司
 * author: jack_guo
 */

namespace app\forms\mall\export;

use app\core\CsvExport;
use app\models\Jiayou;
use app\models\JiayouOrder;
use app\models\Order;
use app\models\Store;

class SendStatisticsExport extends BaseExport
{

    public $type;

    public function fieldsList()
    {
        return [
            [
                'key' => 'date',
                'value' => '日期',
            ],
            [
                'key' => 'name',
                'value' => '名称',
            ],
            [
                'key' => 'all_num',
                'value' => '发放总数',
            ],
            [
                'key' => 'use_num',
                'value' => '已使用数量',
            ],
            [
                'key' => 'unuse_num',
                'value' => '未使用数量',
            ],
            [
                'key' => 'end_num',
                'value' => '已失效数量',
            ],
        ];
    }

    public function export($query)
    {
        $list = $query->groupBy('`date`,name')
            ->asArray()
            ->all();
        $this->transform($list);
        $this->getFields();
        $dataList = $this->getDataList();
        if ($this->type == 'card') {
            $name = '卡券-';
        } else {
            $name = '优惠券-';
        }

        $fileName = $name . '发放统计' . date('YmdHis');

        (new CsvExport())->export($dataList, $this->fieldsNameList, $fileName);
    }



    public function export1($query)
    {
        $list = JiayouOrder::find()
            ->alias('a')
            ->leftJoin(['b' => Jiayou::tableName()], 'b.id=a.jiayou_id')
            ->leftJoin(['c' => Order::tableName()], 'c.id=a.order_id')
            ->leftJoin(['d' => Store::tableName()], 'd.id=b.store_id')
            ->select('a.id,c.created_at as date,d.name as storeName,b.qianghao,b.youxing,c.total_pay_price,c.coupon_discount_price,b.js_money')
            ->where($query)
            ->asArray()
            ->all();

        if ($this->type == 'card') {
            $name = '加油券-';
        } else {
            $name = '加油券-';
        }

        $listNew = [];
        if($list) {
            foreach ($list as $k => $v) {
                 $v  = array_values($v);
                 $listNew[] = $v;
            }
        }


        $fileName = $name . '发放统计' . date('YmdHis');

        $fieldsNameList = ['序号','日期','加油站','枪号','油型','实付金额','优惠券优惠','直降'];

        (new CsvExport())->export($list, $fieldsNameList, $fileName);
    }


    protected function transform($list)
    {
        $newList = [];
        $arr = [];

        $number = 1;
        foreach ($list as $key => $item) {
            $arr['number'] = $number++;
            $item['all_num'] = intval($item['all_num']);
            $item['use_num'] = intval($item['use_num']);
            $item['unuse_num'] = intval($item['unuse_num']);
            $item['end_num'] = intval($item['end_num']);

            $arr = array_merge($arr, $item);


            $newList[] = $arr;
        }
        $this->dataList = $newList;
    }

    protected function getFields()
    {
        $arr = [];
        foreach ($this->fieldsList() as $key => $item) {
            $arr[$key] = $item['key'];
        }
        $this->fieldsKeyList = $arr;
        parent::getFields(); // TODO: Change the autogenerated stub
    }
}
