// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getimg/getImg.proto

package getimg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetImg service

func NewGetImgEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetImg service

type GetImgService interface {
	MicroGetImg(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetImg_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (GetImg_PingPongService, error)
}

type getImgService struct {
	c    client.Client
	name string
}

func NewGetImgService(name string, c client.Client) GetImgService {
	return &getImgService{
		c:    c,
		name: name,
	}
}

func (c *getImgService) MicroGetImg(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetImg.MicroGetImg", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getImgService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetImg_StreamService, error) {
	req := c.c.NewRequest(c.name, "GetImg.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getImgServiceStream{stream}, nil
}

type GetImg_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type getImgServiceStream struct {
	stream client.Stream
}

func (x *getImgServiceStream) Close() error {
	return x.stream.Close()
}

func (x *getImgServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImgServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImgServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImgServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *getImgService) PingPong(ctx context.Context, opts ...client.CallOption) (GetImg_PingPongService, error) {
	req := c.c.NewRequest(c.name, "GetImg.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getImgServicePingPong{stream}, nil
}

type GetImg_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type getImgServicePingPong struct {
	stream client.Stream
}

func (x *getImgServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *getImgServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *getImgServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImgServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImgServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *getImgServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetImg service

type GetImgHandler interface {
	MicroGetImg(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, GetImg_StreamStream) error
	PingPong(context.Context, GetImg_PingPongStream) error
}

func RegisterGetImgHandler(s server.Server, hdlr GetImgHandler, opts ...server.HandlerOption) error {
	type getImg interface {
		MicroGetImg(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type GetImg struct {
		getImg
	}
	h := &getImgHandler{hdlr}
	return s.Handle(s.NewHandler(&GetImg{h}, opts...))
}

type getImgHandler struct {
	GetImgHandler
}

func (h *getImgHandler) MicroGetImg(ctx context.Context, in *Request, out *Response) error {
	return h.GetImgHandler.MicroGetImg(ctx, in, out)
}

func (h *getImgHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetImgHandler.Stream(ctx, m, &getImgStreamStream{stream})
}

type GetImg_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type getImgStreamStream struct {
	stream server.Stream
}

func (x *getImgStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getImgStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImgStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImgStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImgStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *getImgHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GetImgHandler.PingPong(ctx, &getImgPingPongStream{stream})
}

type GetImg_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type getImgPingPongStream struct {
	stream server.Stream
}

func (x *getImgPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *getImgPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImgPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImgPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImgPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *getImgPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
