// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/postret.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Postret service

func NewPostretEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Postret service

type PostretService interface {
	Register(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Postret_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Postret_PingPongService, error)
}

type postretService struct {
	c    client.Client
	name string
}

func NewPostretService(name string, c client.Client) PostretService {
	return &postretService{
		c:    c,
		name: name,
	}
}

func (c *postretService) Register(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Postret.Register", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postretService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Postret_StreamService, error) {
	req := c.c.NewRequest(c.name, "Postret.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &postretServiceStream{stream}, nil
}

type Postret_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type postretServiceStream struct {
	stream client.Stream
}

func (x *postretServiceStream) Close() error {
	return x.stream.Close()
}

func (x *postretServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postretServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postretServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postretServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postretService) PingPong(ctx context.Context, opts ...client.CallOption) (Postret_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Postret.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postretServicePingPong{stream}, nil
}

type Postret_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type postretServicePingPong struct {
	stream client.Stream
}

func (x *postretServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *postretServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *postretServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postretServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postretServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *postretServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Postret service

type PostretHandler interface {
	Register(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Postret_StreamStream) error
	PingPong(context.Context, Postret_PingPongStream) error
}

func RegisterPostretHandler(s server.Server, hdlr PostretHandler, opts ...server.HandlerOption) error {
	type postret interface {
		Register(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Postret struct {
		postret
	}
	h := &postretHandler{hdlr}
	return s.Handle(s.NewHandler(&Postret{h}, opts...))
}

type postretHandler struct {
	PostretHandler
}

func (h *postretHandler) Register(ctx context.Context, in *Request, out *Response) error {
	return h.PostretHandler.Register(ctx, in, out)
}

func (h *postretHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PostretHandler.Stream(ctx, m, &postretStreamStream{stream})
}

type Postret_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type postretStreamStream struct {
	stream server.Stream
}

func (x *postretStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postretStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postretStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postretStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postretStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *postretHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.PostretHandler.PingPong(ctx, &postretPingPongStream{stream})
}

type Postret_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type postretPingPongStream struct {
	stream server.Stream
}

func (x *postretPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *postretPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postretPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postretPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postretPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *postretPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
