// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/postlogin/postlogin.proto

package postlogin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Postlogin service

func NewPostloginEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Postlogin service

type PostloginService interface {
	Login(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Postlogin_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Postlogin_PingPongService, error)
}

type postloginService struct {
	c    client.Client
	name string
}

func NewPostloginService(name string, c client.Client) PostloginService {
	return &postloginService{
		c:    c,
		name: name,
	}
}

func (c *postloginService) Login(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Postlogin.Login", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postloginService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Postlogin_StreamService, error) {
	req := c.c.NewRequest(c.name, "Postlogin.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &postloginServiceStream{stream}, nil
}

type Postlogin_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type postloginServiceStream struct {
	stream client.Stream
}

func (x *postloginServiceStream) Close() error {
	return x.stream.Close()
}

func (x *postloginServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postloginServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postloginServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postloginServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postloginService) PingPong(ctx context.Context, opts ...client.CallOption) (Postlogin_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Postlogin.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postloginServicePingPong{stream}, nil
}

type Postlogin_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type postloginServicePingPong struct {
	stream client.Stream
}

func (x *postloginServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *postloginServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *postloginServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postloginServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postloginServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *postloginServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Postlogin service

type PostloginHandler interface {
	Login(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Postlogin_StreamStream) error
	PingPong(context.Context, Postlogin_PingPongStream) error
}

func RegisterPostloginHandler(s server.Server, hdlr PostloginHandler, opts ...server.HandlerOption) error {
	type postlogin interface {
		Login(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Postlogin struct {
		postlogin
	}
	h := &postloginHandler{hdlr}
	return s.Handle(s.NewHandler(&Postlogin{h}, opts...))
}

type postloginHandler struct {
	PostloginHandler
}

func (h *postloginHandler) Login(ctx context.Context, in *Request, out *Response) error {
	return h.PostloginHandler.Login(ctx, in, out)
}

func (h *postloginHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PostloginHandler.Stream(ctx, m, &postloginStreamStream{stream})
}

type Postlogin_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type postloginStreamStream struct {
	stream server.Stream
}

func (x *postloginStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postloginStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postloginStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postloginStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postloginStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *postloginHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.PostloginHandler.PingPong(ctx, &postloginPingPongStream{stream})
}

type Postlogin_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type postloginPingPongStream struct {
	stream server.Stream
}

func (x *postloginPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *postloginPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postloginPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postloginPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postloginPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *postloginPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
