// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getuserhouses/getuserhouses.proto

package getuserhouses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Getuserhouses service

func NewGetuserhousesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Getuserhouses service

type GetuserhousesService interface {
	Getuserhousescd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Postuserhousecd(ctx context.Context, in *PostRequest, opts ...client.CallOption) (*PostResponse, error)
	UploadHouseImg(ctx context.Context, in *UploadImgRequest, opts ...client.CallOption) (*UploadImgResponse, error)
	SearchHouses(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	GetIndex(ctx context.Context, in *IndexRequest, opts ...client.CallOption) (*IndexResponse, error)
	GetHousesDetail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error)
}

type getuserhousesService struct {
	c    client.Client
	name string
}

func NewGetuserhousesService(name string, c client.Client) GetuserhousesService {
	return &getuserhousesService{
		c:    c,
		name: name,
	}
}

func (c *getuserhousesService) Getuserhousescd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Getuserhouses.Getuserhousescd", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getuserhousesService) Postuserhousecd(ctx context.Context, in *PostRequest, opts ...client.CallOption) (*PostResponse, error) {
	req := c.c.NewRequest(c.name, "Getuserhouses.Postuserhousecd", in)
	out := new(PostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getuserhousesService) UploadHouseImg(ctx context.Context, in *UploadImgRequest, opts ...client.CallOption) (*UploadImgResponse, error) {
	req := c.c.NewRequest(c.name, "Getuserhouses.UploadHouseImg", in)
	out := new(UploadImgResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getuserhousesService) SearchHouses(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.name, "Getuserhouses.SearchHouses", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getuserhousesService) GetIndex(ctx context.Context, in *IndexRequest, opts ...client.CallOption) (*IndexResponse, error) {
	req := c.c.NewRequest(c.name, "Getuserhouses.GetIndex", in)
	out := new(IndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getuserhousesService) GetHousesDetail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error) {
	req := c.c.NewRequest(c.name, "Getuserhouses.GetHousesDetail", in)
	out := new(DetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Getuserhouses service

type GetuserhousesHandler interface {
	Getuserhousescd(context.Context, *Request, *Response) error
	Postuserhousecd(context.Context, *PostRequest, *PostResponse) error
	UploadHouseImg(context.Context, *UploadImgRequest, *UploadImgResponse) error
	SearchHouses(context.Context, *SearchRequest, *SearchResponse) error
	GetIndex(context.Context, *IndexRequest, *IndexResponse) error
	GetHousesDetail(context.Context, *DetailRequest, *DetailResponse) error
}

func RegisterGetuserhousesHandler(s server.Server, hdlr GetuserhousesHandler, opts ...server.HandlerOption) error {
	type getuserhouses interface {
		Getuserhousescd(ctx context.Context, in *Request, out *Response) error
		Postuserhousecd(ctx context.Context, in *PostRequest, out *PostResponse) error
		UploadHouseImg(ctx context.Context, in *UploadImgRequest, out *UploadImgResponse) error
		SearchHouses(ctx context.Context, in *SearchRequest, out *SearchResponse) error
		GetIndex(ctx context.Context, in *IndexRequest, out *IndexResponse) error
		GetHousesDetail(ctx context.Context, in *DetailRequest, out *DetailResponse) error
	}
	type Getuserhouses struct {
		getuserhouses
	}
	h := &getuserhousesHandler{hdlr}
	return s.Handle(s.NewHandler(&Getuserhouses{h}, opts...))
}

type getuserhousesHandler struct {
	GetuserhousesHandler
}

func (h *getuserhousesHandler) Getuserhousescd(ctx context.Context, in *Request, out *Response) error {
	return h.GetuserhousesHandler.Getuserhousescd(ctx, in, out)
}

func (h *getuserhousesHandler) Postuserhousecd(ctx context.Context, in *PostRequest, out *PostResponse) error {
	return h.GetuserhousesHandler.Postuserhousecd(ctx, in, out)
}

func (h *getuserhousesHandler) UploadHouseImg(ctx context.Context, in *UploadImgRequest, out *UploadImgResponse) error {
	return h.GetuserhousesHandler.UploadHouseImg(ctx, in, out)
}

func (h *getuserhousesHandler) SearchHouses(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.GetuserhousesHandler.SearchHouses(ctx, in, out)
}

func (h *getuserhousesHandler) GetIndex(ctx context.Context, in *IndexRequest, out *IndexResponse) error {
	return h.GetuserhousesHandler.GetIndex(ctx, in, out)
}

func (h *getuserhousesHandler) GetHousesDetail(ctx context.Context, in *DetailRequest, out *DetailResponse) error {
	return h.GetuserhousesHandler.GetHousesDetail(ctx, in, out)
}
